"""Initial schema with server defaults

Revision ID: 213ddf7d9ff1
Revises: 
Create Date: 2025-11-16 04:15:00.572614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '213ddf7d9ff1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('words', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('syntactic_relation', sa.String(length=50), nullable=True),
    sa.Column('frequency_score', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('significance_score', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('example_sentences', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collocation_phrase_lang', 'collocations', ['phrase', 'language'], unique=True)
    op.create_index(op.f('ix_collocations_language'), 'collocations', ['language'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('native_language', sa.String(length=10), nullable=False),
    sa.Column('target_languages', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('texts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('author', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('unique_words', sa.Integer(), nullable=True),
    sa.Column('readability_score', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('difficulty_level', sa.String(length=10), nullable=True),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('has_alignment', sa.Boolean(), nullable=False),
    sa.Column('alignment_data', sa.JSON(), nullable=True),
    sa.Column('times_read', sa.Integer(), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_texts_fts', 'texts', ['content_tsv'], unique=False, postgresql_using='gin')
    op.create_index('idx_texts_user_lang', 'texts', ['user_id', 'language'], unique=False)
    op.create_index(op.f('ix_texts_language'), 'texts', ['language'], unique=False)
    op.create_index(op.f('ix_texts_user_id'), 'texts', ['user_id'], unique=False)
    op.create_table('user_collocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('collocation_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), nullable=False),
    sa.Column('times_encountered', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collocation_id'], ['collocations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_coll', 'user_collocations', ['user_id', 'collocation_id'], unique=True)
    op.create_index(op.f('ix_user_collocations_user_id'), 'user_collocations', ['user_id'], unique=False)
    op.create_table('user_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_words', sa.Integer(), server_default='0', nullable=False),
    sa.Column('words_learning', sa.Integer(), server_default='0', nullable=False),
    sa.Column('words_known', sa.Integer(), server_default='0', nullable=False),
    sa.Column('words_mastered', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_texts_read', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_reading_time_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_words_read', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_reviews', sa.Integer(), server_default='0', nullable=False),
    sa.Column('current_streak_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('audio_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('has_alignment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_user_id'), 'audio_files', ['user_id'], unique=False)
    op.create_table('reading_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=False),
    sa.Column('completion_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('words_looked_up', sa.Integer(), nullable=False),
    sa.Column('reading_time_seconds', sa.Integer(), nullable=False),
    sa.Column('sessions_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_progress_user_text', 'reading_progress', ['user_id', 'text_id'], unique=True)
    op.create_index(op.f('ix_reading_progress_user_id'), 'reading_progress', ['user_id'], unique=False)
    op.create_table('vocabulary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('surface_form', sa.Text(), nullable=False),
    sa.Column('dictionary_form', sa.Text(), nullable=False),
    sa.Column('reading', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('definitions', sa.JSON(), nullable=False),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('context_source_id', sa.UUID(), nullable=True),
    sa.Column('context_position', sa.Integer(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=50), nullable=True),
    sa.Column('word_type', sa.String(length=20), nullable=False),
    sa.Column('difficulty_level', sa.String(length=10), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['context_source_id'], ['texts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vocab_lang_level', 'vocabulary', ['language', 'difficulty_level'], unique=False)
    op.create_index('idx_vocab_user_dict', 'vocabulary', ['user_id', 'dictionary_form', 'language'], unique=True)
    op.create_index(op.f('ix_vocabulary_language'), 'vocabulary', ['language'], unique=False)
    op.create_index(op.f('ix_vocabulary_user_id'), 'vocabulary', ['user_id'], unique=False)
    op.create_table('audio_alignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audio_file_id', sa.UUID(), nullable=False),
    sa.Column('text_id', sa.UUID(), nullable=False),
    sa.Column('alignments', sa.JSON(), nullable=False),
    sa.Column('alignment_method', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['text_id'], ['texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alignment_audio', 'audio_alignments', ['audio_file_id'], unique=True)
    op.create_table('vocab_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vocab_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('easiness_factor', sa.DECIMAL(precision=3, scale=2), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('correct_reviews', sa.Integer(), nullable=False),
    sa.Column('last_review_grade', sa.Integer(), nullable=True),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('leech_threshold', sa.Integer(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('graduated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabulary.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cards_due', 'vocab_cards', ['user_id', 'due_date'], unique=False)
    op.create_index('idx_cards_status', 'vocab_cards', ['user_id', 'status'], unique=False)
    op.create_index('idx_cards_vocab_user', 'vocab_cards', ['vocab_id', 'user_id'], unique=True)
    op.create_index(op.f('ix_vocab_cards_due_date'), 'vocab_cards', ['due_date'], unique=False)
    op.create_index(op.f('ix_vocab_cards_user_id'), 'vocab_cards', ['user_id'], unique=False)
    op.create_table('review_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('review_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('time_spent_ms', sa.Integer(), nullable=True),
    sa.Column('interval_before', sa.Integer(), nullable=True),
    sa.Column('easiness_before', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('interval_after', sa.Integer(), nullable=True),
    sa.Column('easiness_after', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('review_type', sa.String(length=20), nullable=False),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['vocab_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_logs_user_date', 'review_logs', ['user_id', 'review_date'], unique=False)
    op.create_index(op.f('ix_review_logs_review_date'), 'review_logs', ['review_date'], unique=False)
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_review_date'), table_name='review_logs')
    op.drop_index('idx_review_logs_user_date', table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_index(op.f('ix_vocab_cards_user_id'), table_name='vocab_cards')
    op.drop_index(op.f('ix_vocab_cards_due_date'), table_name='vocab_cards')
    op.drop_index('idx_cards_vocab_user', table_name='vocab_cards')
    op.drop_index('idx_cards_status', table_name='vocab_cards')
    op.drop_index('idx_cards_due', table_name='vocab_cards')
    op.drop_table('vocab_cards')
    op.drop_index('idx_alignment_audio', table_name='audio_alignments')
    op.drop_table('audio_alignments')
    op.drop_index(op.f('ix_vocabulary_user_id'), table_name='vocabulary')
    op.drop_index(op.f('ix_vocabulary_language'), table_name='vocabulary')
    op.drop_index('idx_vocab_user_dict', table_name='vocabulary')
    op.drop_index('idx_vocab_lang_level', table_name='vocabulary')
    op.drop_table('vocabulary')
    op.drop_index(op.f('ix_reading_progress_user_id'), table_name='reading_progress')
    op.drop_index('idx_progress_user_text', table_name='reading_progress')
    op.drop_table('reading_progress')
    op.drop_index(op.f('ix_audio_files_user_id'), table_name='audio_files')
    op.drop_table('audio_files')
    op.drop_table('user_stats')
    op.drop_index(op.f('ix_user_collocations_user_id'), table_name='user_collocations')
    op.drop_index('idx_user_coll', table_name='user_collocations')
    op.drop_table('user_collocations')
    op.drop_index(op.f('ix_texts_user_id'), table_name='texts')
    op.drop_index(op.f('ix_texts_language'), table_name='texts')
    op.drop_index('idx_texts_user_lang', table_name='texts')
    op.drop_index('idx_texts_fts', table_name='texts', postgresql_using='gin')
    op.drop_table('texts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_collocations_language'), table_name='collocations')
    op.drop_index('idx_collocation_phrase_lang', table_name='collocations')
    op.drop_table('collocations')
    # ### end Alembic commands ###
